### ISSUE TITLE
JDK11: BAD LDC: 17 (Dynamic Class-File Constants)

### ISSUE THREAD

**Issue by harshilps** [jboss-javassist/javassist#282] opened 2019-10-16 23:10 UTC
#270 I thought that the PR/merge would make javassist fully compatible with Dynamic Class-File Constants(https://openjdk.java.net/jeps/309). When running junit tests using powermock on the Java 11 I get this error: "BAD LDC 17". Here Javassist and Mockito is used as a dependency of PowerMock. 
I am using the following versions.

1. Javassist 3.26.0-GA  
2. PowerMock 2.0.2
3. JDK 11
4. Mockito 2.28.0

**Comment by valfirst** [comment] 2019-10-17 11:51
I've faced with this issue as well, here is an exception stack trace:
```
...
Caused by: java.lang.RuntimeException: bad LDC: 17
	at javassist.bytecode.stackmap.Tracer.doLDC(Tracer.java:267)
	at javassist.bytecode.stackmap.Tracer.doOpcode0_53(Tracer.java:167)
	at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:73)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:195)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:172)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:116)
	at javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:458)
	at javassist.bytecode.MethodInfo.rebuildStackMapIf6(MethodInfo.java:440)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:118)
	at javassist.CtClassType.instrument(CtClassType.java:1541)
	at org.powermock.core.transformers.javassist.InstrumentMockTransformer.transform(InstrumentMockTransformer.java:41)
	at org.powermock.core.transformers.javassist.AbstractJavaAssistMockTransformer.transform(AbstractJavaAssistMockTransformer.java:40)
	at org.powermock.core.transformers.support.DefaultMockTransformerChain.transform(DefaultMockTransformerChain.java:43)
	at org.powermock.core.classloader.MockClassLoader.transformClass(MockClassLoader.java:184)
	at org.powermock.core.classloader.javassist.JavassistMockClassLoader.defineAndTransformClass(JavassistMockClassLoader.java:102)
	... 106 more
```

**Comment by harshilps** [comment] 2019-10-17 16:33
Did you get around solving it? or like do you have any fix for this issue?

**Comment by chibash** [comment] 2019-10-17 16:35
I'll check this.

**Comment by harshilps** [comment] 2019-11-26 17:58
> I'll check this.

Any updates on a fix?

**Comment by chibash** [comment] 2019-11-27 11:14
Not yet, but I'm working on this.

**Comment by tiagorico** [comment] 2019-12-19 02:50
Any update on this?

**Comment by chibash** [comment] 2019-12-23 00:59
Is there anyone who kindly writes a Java source file that is compiled into a class file including the bytecode ldc with CONSTANT_Dynamic?

**Comment by chibash** [comment] 2019-12-23 09:39
Can anyone check javassist.jar available from master/HEAD?
I hope it will fix the bug.

**Comment by SurpSG** [comment] 2019-12-23 12:32
Hi @chibash 
Seems, the issue if fixed with `javassist.jar from master/HEAD`

**Comment by chibash** [comment] 2019-12-23 13:43
Great, thanks to @SurpSG

**Comment by harshilps** [comment] 2019-12-24 17:35
@chibash Are there any plans to release a new version with this feature any time soon?

**Comment by chibash** [comment] 2019-12-24 17:36
Until the end of this year?

**Comment by harshilps** [comment] 2019-12-24 17:40
Not particularly before the end of this year just in general.

**Comment by valfirst** [comment] 2020-02-20 10:00
@chibash do you have plans to release a new version in the near future?

**Comment by andreimozgo** [comment] 2020-03-17 12:29
@chibash @valfirst Could you please release a new version?

**Comment by valfirst** [comment] 2020-03-17 14:27
@andreimozgo I'm just a contributor, I can't release it, I'm waiting for release as you and anybody else 😄

**Comment by chibash** [comment] 2020-03-17 14:45
Sorry for my silence.  I'll release within a day.

**Comment by chibash** [comment] 2020-03-18 18:17
I have done.  The new release will be available soon from maven (but I must ask someone else to upload).

**Comment by lewe518** [comment] 2020-03-19 07:48
@chibash Could you please upload the new version to mvnrepository ?

**Comment by chibash** [comment] 2020-03-19 08:02
I don't have an access permission.

**Comment by chibash** [comment] 2020-03-19 13:55
Now it's on maven.

**Comment by bergerst** [comment] 2020-05-12 09:03
So can this issue be closed?

**Closed** 2020-05-12 10:47 UTC

**Comment by ArtKE** [comment] 2020-06-10 08:50
Did anybody find working versions combination? i try to migrate to java 11 and have the same issue.
i use: 
JDK 11
mockito-core : 2.28.0
powermock-module-junit4: 2.0.2
powermock-api-mockito2: 2.0.2
javassist: 3.26.0-GA

still have 
`java.lang.IllegalStateException: Failed to transform class with name <someclass>. Reason: bad LDC: 17
Caused by: java.lang.RuntimeException: bad LDC: 17
`

tried to play with versions in different cases have different exception.

**Comment by valfirst** [comment] 2020-06-10 08:52
@ArtKE I recommend to use PowerMock `2.0.6` and higher

**Comment by ArtKE** [comment] 2020-06-10 09:20
tried with higher versions
PowerMock 2.0.6
Mockito 3.3.3
javassist 3.27.0-GA
still have
 `java.lang.IllegalStateException: Failed to transform class with name <name>. Reason: bad LDC: 17
Caused by: java.lang.RuntimeException: bad LDC: 17`

**Comment by valfirst** [comment] 2020-06-10 09:23
@ArtKE could you please make sure you don't have another version of javassist in classpath? also could you post the full exception stacktrace?

**Comment by ArtKE** [comment] 2020-06-10 09:43
powermock-module-junit4:2.0.7 has javassist 3.27.0-GA within itself so i deleted my extra dependency. so now i have 
PowerMock 2.0.6
Mockito 3.3.3
Java 11

**Comment by lighTQ** [comment] 2020-07-30 06:24
I add this for my testClass it solved the problem，you should try it again. may be can solve your problem.

@SuppressStaticInitializationFor("org.apache.hadoop.fs.FileSystem") 
@RunWith(PowerMockRunner.class)
@PowerMockIgnore("javax.management.*") // resolve classloader conflict

* PowerMockit 2.02 
* JDK 1.8

**Comment by vikaskhengare** [comment] 2020-08-20 23:00
Hi All,

We are trying to migrate the code from JDK 8 to 11. Old code was using old versions of javassist, powermock and mockito.

Now we are trying with following combination,
javassist - 3.27.0-GA
powermock - 2.0.2
mockito - 2.28.2
JDK - 11

While doing this, we got following error,
**java.lang.IllegalStateException: Failed to transform class with name com.mycompany.constant.MyConstants. Reason: com.mycompany.constant.MyConstants$SomeEnum class is frozen**

```
java.lang.IllegalStateException: Failed to transform class with name com.mycompany.constant.MyConstants. Reason: com.mycompany.constant.MyConstants$SomeEnum class is frozen
	at org.powermock.core.classloader.javassist.JavassistMockClassLoader.defineAndTransformClass(JavassistMockClassLoader.java:119)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:174)
	at org.powermock.core.classloader.MockClassLoader.loadClassByThisClassLoader(MockClassLoader.java:102)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:147)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:98)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.cisco.config.base.logger.ConfigLiteLoggerFactory.isDownloadSessionLoggerEnabled(ConfigLiteLoggerFactory.java:195)
	at com.cisco.config.base.logger.ConfigLiteLogger.getLogger(ConfigLiteLogger.java:453)
	at com.cisco.config.base.logger.ConfigLiteLogger.error(ConfigLiteLogger.java:413)
	at com.cisco.config.meraki.resource.FinalResponseResource.getDoneResponse(FinalResponseResource.java:70)
	at com.cisco.config.meraki.resource.test.FinalResponseResourceTest.getDoneResponseTest(FinalResponseResourceTest.java:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:326)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:88)
...
...
Caused by: java.lang.RuntimeException: com.mycompany.constant.MyConstants$SomeEnum class is frozen
	at javassist.CtClassType.checkModify(CtClassType.java:321)
	at javassist.CtBehavior.setModifiers(CtBehavior.java:178)
	at org.powermock.core.transformers.javassist.ConstructorsMockTransformer.transform(ConstructorsMockTransformer.java:64)
	at org.powermock.core.transformers.javassist.ConstructorsMockTransformer.transform(ConstructorsMockTransformer.java:51)
	at org.powermock.core.transformers.javassist.AbstractJavaAssistMockTransformer.transform(AbstractJavaAssistMockTransformer.java:40)
	at org.powermock.core.transformers.support.DefaultMockTransformerChain.transform(DefaultMockTransformerChain.java:43)
	at org.powermock.core.classloader.MockClassLoader.transformClass(MockClassLoader.java:184)
	at org.powermock.core.classloader.javassist.JavassistMockClassLoader.defineAndTransformClass(JavassistMockClassLoader.java:102)

```
Does anyone know why do we get this error and how to resolve it?

What do class frozen means?

Thanks in advance!
